---
title: "Coding Experiment EDA | W241 Final Project"
author: "Arunima Kayath, Daniel Rasband, Payman Rhogani"
date: \today
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(magrittr)
```


```{r}
d <- read.csv("CodingExperimentFinalResults.csv")
dt <- as.data.table(d)
head(dt)
```

```{r}
names(dt)
```

```{r}
dt[, .('Avg Years Experience' = mean(years_experience)), keyby=control_first]
```

```{r}
dt[, .N, keyby=.(age, control_first)]
```

```{r}
dt[, .N, keyby=test_set_name]
```


```{r}
dt[, .N, keyby=.(team_size, control_first)]
```

```{r}
# Non-compliance
dt[pre_task_treat == 0, .N, keyby=control_first]
```

```{r}
# Placebo non-compliance
dt[pre_task_control == 0, .N, keyby=control_first]
```


```{r}
# Post-treatment attrition
nrow(dt[(week1_attempted==1) & (week2_attempted==0)])
```

```{r}
dt[, .N, keyby=control_first]
```

```{r}
both_attempted = dt[(week1_attempted==1) & (week2_attempted==1)]
both_attempted[, .N, keyby=control_first]
```

```{r}
both_attempted[, .('Average Week 1 Score' = mean(w1_score)), keyby=control_first]
```

```{r}
both_attempted[, .('Average Week 2 Score' = mean(w2_score)), keyby=control_first]
```

```{r}
both_attempted[, control_score := ifelse(control_first==1, w1_score, w2_score)]
both_attempted[, treatment_score := ifelse(control_first==1, w2_score, w1_score)]
both_attempted[, .('Average Control Score' = mean(control_score), 'Average Treatment Score' = mean(treatment_score))]

t.test(both_attempted$control_score, both_attempted$treatment_score)
```

```{r}
both_attempted[, .(
  'Average Control Score' = mean(control_score), 
  'Average Treatment Score' = mean(treatment_score)), 
  keyby=upwork]
```


```{r}
both_attempted[control_first==1, control_time := w1_t1_t2_mins]
both_attempted[control_first==1, treatment_time := w2_t1_t2_mins]
both_attempted[control_first==0, control_time := w2_t1_t2_mins]
both_attempted[control_first==0, treatment_time := w1_t1_t2_mins]
both_attempted[, .('Average Control Time for First 2 Tasks' = mean(control_time), 'Average Treatment Time for First 2 Tasks' = mean(treatment_time))]
```

```{r}
both_attempted[, .('Average Control Time for First 2 Tasks' = mean(control_time), 'Average Treatment Time for First 2 Tasks' = mean(treatment_time)), keyby=control_first]
```

```{r}
dt[week1_attempted == 1, .('Week 1 Score' = mean(w1_score), 'Week 1 Time' = mean(w1_t1_t2_mins)), keyby=control_first]
```


```{r}
dt[week2_attempted==1, .('Week 2 Score' = mean(w2_score), 'Week 2 Time' = mean(w2_t1_t2_mins)), keyby=.(upwork, control_first)]
```

```{r}
dt[week1_attempted == 1, .N, keyby=upwork]
both_attempted[, .N, keyby=upwork]
```

```{r}
par(mfrow=c(3,2))
dt[, hist(w1_t1_mins)]
dt[, hist(w1_t1_score)]
dt[, hist(w1_t2_mins)]
dt[, hist(w1_t2_score)]
dt[, hist(w1_t3_mins)]
dt[, hist(w1_t3_score)]

par(mfrow=c(3, 2))
dt[, hist(w2_t1_mins)]
dt[, hist(w2_t1_score)]
dt[, hist(w2_t2_mins)]
dt[, hist(w2_t2_score)]
dt[, hist(w2_t3_mins)]
dt[, hist(w2_t3_score)]
```

```{r}
par(mfrow=c(4, 2))
for (val in unique(dt$test_set_name)) {
  both_attempted[test_set_name==val, hist(w1_t2_score, breaks = 10, main=val)]
}
```

```{r}
par(mfrow=c(4, 2))
for (val in unique(dt$test_set_name)) {
  both_attempted[test_set_name==val, hist(w2_t2_score, breaks = 10, main=val)]
}
```

```{r}
dt[w1_t2_id == 3, p3_score := w1_t2_score]
dt[w1_t2_id == 3, p3_mins := w1_t2_mins]
dt[w1_t2_id == 4, p3_score := w2_t2_score]
dt[w1_t2_id == 4, p3_mins := w2_t2_mins]
dt[w1_t2_id == 4, p4_score := w1_t2_score]
dt[w1_t2_id == 4, p4_mins := w1_t2_mins]
dt[w1_t2_id == 3, p4_score := w2_t2_score]
dt[w1_t2_id == 3, p4_mins := w2_t2_mins]
dt[w1_t3_id == 5, p5_score := w1_t3_score]
dt[w1_t3_id == 5, p5_mins := w1_t3_mins]
dt[w1_t3_id == 5, p6_score := w2_t3_score]
dt[w1_t3_id == 5, p6_mins := w2_t3_mins]
dt[w1_t3_id == 6, p5_score := w2_t3_score]
dt[w1_t3_id == 6, p5_mins := w2_t3_mins]
dt[w1_t3_id == 6, p6_score := w1_t3_score]
dt[w1_t3_id == 6, p6_mins := w1_t3_mins]
```

```{r}
par(mfrow=c(2, 2))
dt[, hist(w1_t1_score, breaks = 20, main='Problem 1 Scores')]
dt[, hist(w1_t1_mins, breaks = 10, main='Problem 1 Mins')]
dt[, hist(w2_t1_score, breaks = 20, main='Problem 2 Score')]
dt[, hist(w2_t1_mins, breaks = 10, main='Problem 2 Mins')]

par(mfrow=c(2, 2))
dt[, hist(p3_score, breaks = 20, main='Problem 3 Scores')]
dt[, hist(p3_mins, breaks = 10, main='Problem 3 Mins')]
dt[, hist(p4_score, breaks = 20, main='Problem 4 Score')]
dt[, hist(p4_mins, breaks = 10, main='Problem 4 Mins')]

par(mfrow=c(2, 2))
dt[, hist(p5_score, breaks = 20, main='Problem 5 Score')]
dt[, hist(p5_mins, breaks = 10, main='Problem 5 Mins')]
dt[, hist(p6_score, breaks = 20, main='Problem 6 Score')]
dt[, hist(p6_mins, breaks = 10, main='Problem 6 Mins')]
```

```{r}
summary(lm(w1_score ~ control_first + w1_t2_id + upwork + I(upwork * control_first), data = dt[week1_attempted==1]))
```

```{r}
w1 <- dt[week1_attempted==1]
w2 <- dt[week2_attempted==1]

flattened_n <- nrow(w1) + nrow(w2)

flattened_dt <- data.table(
  t1_t2_mins=c(
    w1[, w1_t1_t2_mins],
    w2[, w2_t1_t2_mins]
  ),
  t1_t2_score=c(
    w1[, (w1_t1_score + w1_t2_score) / 2],
    w2[, (w2_t1_score + w2_t2_score) / 2]
  ),
  time=c(
    w1[, w1_total_mins],
    w2[, w2_total_mins]
  ),
  score=c(
    w1[, w1_score],
    w2[, w2_score]
  ),
  t2_id=c(
    w1[, w1_t2_id],
    w2[, w2_t2_id]
  ),
  treat=c(
    w1[, abs(control_first - 1)],
    w2[, control_first]
  ),
  upwork=c(w1[, upwork], w2[, upwork])
)
```

```{r}
head(flattened_dt)
```

```{r}
summary(lm(t1_t2_score ~ treat + upwork + I(treat * upwork), data = flattened_dt))
```

I want to look at the difference between the first and second week (ignoring attrition for now).

```{r}
both_attempted[control_first == 1, score_diff := w2_score - w1_score]
both_attempted[control_first == 0, score_diff := w1_score - w2_score]
both_attempted[control_first == 1, mins_diff := w2_t1_t2_mins - w1_t1_t2_mins]
both_attempted[control_first == 0, mins_diff := w1_t1_t2_mins - w2_t1_t2_mins]

both_attempted[, mean(score_diff)]
both_attempted[, mean(mins_diff)]
both_attempted[upwork == 0, mean(score_diff)]
both_attempted[upwork == 1, mean(score_diff)]
both_attempted[upwork == 0, mean(mins_diff)]
both_attempted[upwork == 1, mean(mins_diff)]

# Possible spillover?
both_attempted[, mean(score_diff), keyby=control_first]
both_attempted[, mean(mins_diff), keyby=control_first]
```

```{r}
summary(lm(score_diff ~ control_first, data=both_attempted))
```


```{r}
# Calculate the average treatment effect.
ate.hat <- function(dt, outcome, keyby) {
  ate <- dt %>%
    .[ , .(mean_outcome = mean(get(outcome))), keyby=get(keyby)] %>%
    .[ , diff(mean_outcome)]

  return(ate)
}

# Simulate a sharp null distribution.
simulate.sharp.null <- function(n, dt.withZ, outcome) {
  simulate.ate <- function() {
    ate <- dt.withZ %>%
      .[ , .(mean_outcomes = mean(get(outcome))), keyby=sample(Z)] %>%
      .[ , diff(mean_outcomes)]
    return(ate)
  }

  return(replicate(n, simulate.ate()))
}
```

```{r}
both.dist <- simulate.sharp.null(10000, both_attempted[, Z := c(rep(0, .N / 2), rep(1, .N / 2))], "score_diff")
hist(both.dist, breaks = 30)
```

```{r}
length(both.dist[abs(both.dist) > 6.8]) / 10000
```

```{r}
both.mins.dist <- simulate.sharp.null(10000, both_attempted[, Z := c(rep(0, .N / 2), rep(1, .N / 2))], "mins_diff")
hist(both.mins.dist)
```

```{r}
length(both.mins.dist[abs(both.mins.dist) > 0.6222222]) / 10000
```

```{r}
upwork.score.dist <- simulate.sharp.null(10000, both_attempted[upwork == 1, Z := c(rep(0, .N / 2), rep(1, .N / 2))], "score_diff")
hist(upwork.score.dist)
```

```{r}
length(upwork.score.dist[abs(upwork.score.dist) > 10.277]) / 10000
```

```{r}
summary(lm(score_diff ~ upwork + control_first, data = both_attempted))
```

